name: ci-guide
on:
  push:
    paths:
      - guide/**
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: cd guide && mkdocs gh-deploy --force
